FROM docker.io/library/python:3-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    gstreamer1.0-tools \
    libchromaprint-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "beets[chroma,embedart,fetchart,lastgenre,lyrics,scrub]"; \
    pip install --no-cache-dir beets-filetote;

ARG APP_USER=beetsuser
ARG APP_GROUP=beetsgroup
ARG APP_UID=1000
ARG APP_GID=1000

ENV BEETSDIR="/app/config"
ENV HOME="${BEETSDIR}"

RUN groupadd -g ${APP_GID} ${APP_GROUP} && \
    useradd -m -u ${APP_UID} -g ${APP_GROUP} -s /usr/sbin/nologin ${APP_USER}

WORKDIR /app

RUN mkdir -p ${HOME} && \
    chown -R ${APP_USER}:${APP_GROUP} ${HOME}

USER ${APP_USER}

CMD ["sleep", "infinity"]
